//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrmLinqToMySql.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_hzcdatasourceEntities : DbContext
    {
        public db_hzcdatasourceEntities()
            : base("name=db_hzcdatasourceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_basestation> t_basestation { get; set; }
        public virtual DbSet<t_basestationdetail> t_basestationdetail { get; set; }
        public virtual DbSet<t_caseinfo> t_caseinfo { get; set; }
    }
}
