//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrmLinqToMySql.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_basestationdetail
    {
        public int Id { get; set; }
        public int bsId { get; set; }
        public Nullable<int> signalId { get; set; }
        public string LAC { get; set; }
        public string CID { get; set; }
        public string CH { get; set; }
        public string BSIC { get; set; }
        public string RX { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
    }
}
