//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrmLinqToMySql.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_caseinfo
    {
        public int Id { get; set; }
        public string caseToken { get; set; }
        public string caseNo { get; set; }
        public string caseName { get; set; }
        public int caseTypeId { get; set; }
        public System.DateTime caseStart { get; set; }
        public System.DateTime caseEnd { get; set; }
        public double lat { get; set; }
        public double lon { get; set; }
        public string caseAddr { get; set; }
        public string caseDetail { get; set; }
        public string remarks { get; set; }
        public Nullable<long> caseSize { get; set; }
        public int isShare { get; set; }
        public string shareStr { get; set; }
        public Nullable<long> fileSize { get; set; }
        public Nullable<int> picNum { get; set; }
        public Nullable<int> vdeoNum { get; set; }
        public Nullable<int> bsNum { get; set; }
        public Nullable<int> wifiNum { get; set; }
        public string defImg { get; set; }
        public System.DateTime createTime { get; set; }
        public int deptId { get; set; }
        public int userId { get; set; }
        public string userName { get; set; }
        public System.DateTime modifyTime { get; set; }
    }
}
